---
country_name: FR
locality_name: Paris
organization_name: Dr Strange
email_address: email@domain.tld
sql_root_password: root
sql_user: user
sql_user_password: user
sql_database: medshakeehr
msehr_dir: /var/www/ehr
timezone: Europe/Paris
msehr_domain: msehr.local
upload_max_filesize: 20M
post_maxsize: 20M
max_input_vars: 10000
error_reporting: 'E_ALL & ~E_DEPRECATED & ~E_STRICT'
display_errors: 'Off'
display_startup_errors: 'Off'

# VPN
# https://github.com/githubixx/ansible-role-wireguard

wireguard_port: "51820"
wireguard_address: 10.9.0.1/32
wireguard_endpoint: "192.168.1.17:{{ wireguard_port }}"
wireguard_preup:
  - echo 1 > /proc/sys/net/ipv4/ip_forward
wireguard_postup:
  - iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
  - iptables -A FORWARD -i %i -j ACCEPT
  - iptables -A FORWARD -o %i -j ACCEPT
