---
roles: 
  - dev-sec.os-hardening
  - dev-sec.ssh-hardening
  - geerlingguy.firewall
  - jnv.unattended-upgrades
  - geerlingguy.apache
  - geerlingguy.php
  - geerlingguy.mysql
  - dev-sec.mysql-hardening

